services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - type: volume
        source: uploads
        target: /api/uploads/originals
        volume:
          subpath: originals
      - type: volume
        source: uploads
        target: /worker/uploads/processed
        volume:
          subpath: processed
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  
  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  db:
    image: postgres:trixie
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  worker:
    build:
      context: worker/
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - type: volume
        source: uploads
        target: /worker/uploads/originals
        volume:
          subpath: originals
      - type: volume
        source: uploads
        target: /worker/uploads/processed
        volume:
          subpath: processed
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  db-data:
    name: "db_k3s_playground"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mohamed/k3s-playground-volume-db
  uploads:
    name: "uploads"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mohamed/k3s-playground-volume_uploads

