apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: playground
  name: old-task-deleting
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleaning
              image: elbergui/playground-cleaner:v1
              envFrom:
                - configMapRef: 
                    name: config
                - secretRef: 
                    name: secret-config
              volumeMounts:
                - name: images
                  mountPath: /uploads/originals
                  subPath: originals
                - name: images
                  mountPath: /uploads/processed
                  subPath: processed

          restartPolicy: OnFailure
          volumes:
            - name: images
              persistentVolumeClaim:
                claimName: uploads-pvc
    