apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: playground
  labels:
    app: db
spec:
  containers:
    - name: postgres
      image: postgres:trixie
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: POSTGRES_PASSWORD
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: db-volume
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: postgres-pvc
