apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: playground
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
            
     